version: '3.3'

services:
  # MinIO Web Manager 应用
  minio-web-manager:
    build: .
    container_name: minio-web-manager
    restart: unless-stopped
    environment:
      - MINIO_ENDPOINT=http://minio:9000
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=12345678
      - MINIO_BUCKET_NAME=uploads
      - MINIO_SECURE=false
      - MAX_FILE_SIZE=104857600
      - ALLOWED_EXTENSIONS=jpg,jpeg,png,gif,pdf,doc,docx,xls,xlsx,ppt,pptx,txt,zip,rar,mp4,mp3
    depends_on:
      - minio
    volumes:
      - ./config.env:/app/config.env:ro
      - ./logs:/app/logs
    networks:
      - minio-network

  # MinIO 对象存储服务
  minio:
    image: docker-mirror.aigc2d.com/minio/minio:latest
    container_name: minio-server
    restart: unless-stopped
    ports:
      - "9000:9000"  # API端口
      - "9001:9001"  # 控制台端口
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=12345678
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    networks:
      - minio-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  # Nginx 反向代理
  nginx:
    image: docker-mirror.aigc2d.com/nginx:alpine
    container_name: minio-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./ssl:/etc/nginx/ssl:ro  # SSL证书目录（可选）
    depends_on:
      - minio-web-manager
    networks:
      - minio-network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/status"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  minio_data:
    driver: local

networks:
  minio-network:
    driver: bridge 